name: Run Tests
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      extended_tests:
        description: 'Extended tests'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v6
      - run: ./gradlew build check -x test --stacktrace --warning-mode fail
      - uses: Juuxel/publish-checkstyle-report@v3
        if: ${{ failure() }}
        with:
          reports: |
            build/reports/checkstyle/*.xml
            build/reports/codenarc/*.xml
